export const ORGANIZATIONS_REQUEST = 'ORGANIZATIONS_REQUEST';
export const ORGANIZATIONS_SUCCESS = 'ORGANIZATIONS_SUCCESS';
export const ORGANIZATIONS_FAILURE = 'ORGANIZATIONS_FAILURE';

export const ORGANIZATION_REQUEST = 'ORGANIZATION_REQUEST';
export const ORGANIZATION_SUCCESS = 'ORGANIZATION_SUCCESS';
export const ORGANIZATION_FAILURE = 'ORGANIZATION_FAILURE';

export const ORGANIZATION_HOME_REQUEST = 'ORGANIZATION_HOME_REQUEST';
export const ORGANIZATION_HOME_SUCCESS = 'ORGANIZATION_HOME_SUCCESS';
export const ORGANIZATION_HOME_FAILURE = 'ORGANIZATION_HOME_FAILURE';

export const ORGANIZATIONS_BY_TEAM_REQUEST = 'ORGANIZATIONS_BY_TEAM_REQUEST';
export const ORGANIZATIONS_BY_TEAM_SUCCESS = 'ORGANIZATIONS_BY_TEAM_SUCCESS';
export const ORGANIZATIONS_BY_TEAM_FAILURE = 'ORGANIZATIONS_BY_TEAM_FAILURE';

export const ORGANIZATION_ADD_REQUEST = 'ORGANIZATION_ADD_REQUEST';
export const ORGANIZATION_ADD_SUCCESS = 'ORGANIZATION_ADD_SUCCESS';
export const ORGANIZATION_ADD_FAILURE = 'ORGANIZATION_ADD_FAILURE';

export const ORGANIZATION_UPDATE_REQUEST = 'ORGANIZATION_UPDATE_REQUEST';
export const ORGANIZATION_UPDATE_SUCCESS = 'ORGANIZATION_UPDATE_SUCCESS';
export const ORGANIZATION_UPDATE_FAILURE = 'ORGANIZATION_UPDATE_FAILURE';

export const ORGANIZATION_MODE_SET = 'ORGANIZATION_MODE_SET';
export const ORGANIZATION_MODE_RESET = 'ORGANIZATION_MODE_RESET';

export const ORGANIZATION_CODE_REQUEST = 'ORGANIZATION_CODE_REQUEST';
export const ORGANIZATION_CODE_SUCCESS = 'ORGANIZATION_CODE_SUCCESS';
export const ORGANIZATION_CODE_FAILURE = 'ORGANIZATION_CODE_FAILURE';

export const ORGANIZATION_REMOVE_REQUEST = 'ORGANIZATION_REMOVE_REQUEST';
export const ORGANIZATION_REMOVE_SUCCESS = 'ORGANIZATION_REMOVE_SUCCESS';
export const ORGANIZATION_REMOVE_FAILURE = 'ORGANIZATION_REMOVE_FAILURE';
