export const METRICS_QUERY_REQUEST = 'METRICS_QUERY_REQUEST';
export const METRICS_QUERY_SUCCESS = 'METRICS_QUERY_SUCCESS';
export const METRICS_QUERY_FAILURE = 'METRICS_QUERY_FAILURE';

export const METRIC_GET_REQUEST = 'METRIC_GET_REQUEST';
export const METRIC_GET_SUCCESS = 'METRIC_GET_SUCCESS';
export const METRIC_GET_FAILURE = 'METRIC_GET_FAILURE';
