export const SUBMIT_ORGANIZATION_FORM_REQUEST =
  'SUBMIT_ORGANIZATION_FORM_REQUEST';
export const SUBMIT_ORGANIZATION_FORM_SUCCESS =
  'SUBMIT_ORGANIZATION_FORM_SUCCESS';
export const SUBMIT_ORGANIZATION_FORM_FAILURE =
  'SUBMIT_ORGANIZATION_FORM_FAILURE';

export const SUBMIT_NEW_ORGANIZATION_FORM_REQUEST =
  'SUBMIT_NEW_ORGANIZATION_FORM_REQUEST';
export const SUBMIT_NEW_ORGANIZATION_FORM_SUCCESS =
  'SUBMIT_NEW_ORGANIZATION_FORM_SUCCESS';
export const SUBMIT_NEW_ORGANIZATION_FORM_FAILURE =
  'SUBMIT_NEW_ORGANIZATION_FORM_FAILURE';
