export const USER_TEAMS_REQUEST = 'USER_TEAMS_REQUEST';
export const USER_TEAMS_SUCCESS = 'USER_TEAMS_SUCCESS';
export const USER_TEAMS_FAILURE = 'USER_TEAMS_FAILURE';
export const userTeamsResult = [USER_TEAMS_SUCCESS, USER_TEAMS_FAILURE];

export const TEAMS_BY_ORGANIZATION_REQUEST = 'TEAMS_BY_ORGANIZATION_REQUEST';
export const TEAMS_BY_ORGANIZATION_SUCCESS = 'TEAMS_BY_ORGANIZATION_SUCCESS';
export const TEAMS_BY_ORGANIZATION_FAILURE = 'TEAMS_BY_ORGANIZATION_FAILURE';

export const TEAM_REQUEST = 'TEAM_REQUEST';
export const TEAM_SUCCESS = 'TEAM_SUCCESS';
export const TEAM_FAILURE = 'TEAM_FAILURE';

export const TEAM_ONLY_REQUEST = 'TEAM_ONLY_REQUEST';
export const TEAM_ONLY_SUCCESS = 'TEAM_ONLY_SUCCESS';
export const TEAM_ONLY_FAILURE = 'TEAM_ONLY_FAILURE';

export const TEAM_ADD_REQUEST = 'TEAM_ADD_REQUEST';
export const TEAM_ADD_SUCCESS = 'TEAM_ADD_SUCCESS';
export const TEAM_ADD_FAILURE = 'TEAM_ADD_FAILURE';

export const TEAM_UPDATE_REQUEST = 'TEAM_UPDATE_REQUEST';
export const TEAM_UPDATE_SUCCESS = 'TEAM_UPDATE_SUCCESS';
export const TEAM_UPDATE_FAILURE = 'TEAM_UPDATE_FAILURE';

export const TEAM_REMOVE_ORGANIZATION_REQUEST =
  'TEAM_REMOVE_ORGANIZATION_REQUEST';

export const TEAM_REMOVE_REQUEST = 'TEAM_REMOVE_REQUEST';
export const TEAM_REMOVE_SUCCESS = 'TEAM_REMOVE_SUCCESS';
export const TEAM_REMOVE_FAILURE = 'TEAM_REMOVE_FAILURE';

export const TEAM_MODE_SET = 'TEAM_MODE_SET';
export const TEAM_MODE_RESET = 'TEAM_MODE_RESET';
