export const CYCLE_REQUEST_ACTIONS = /^CYCLES?_\w+_REQUEST$/;
export const CYCLE_SUCCESS_ACTIONS = /^CYCLES?_\w+_SUCCESS$/;
export const CYCLE_FAILURE_ACTIONS = /^CYCLES?_\w+_FAILURE$/;

export const CYCLES_GET_REQUEST = 'CYCLES_GET_REQUEST';
export const CYCLES_GET_SUCCESS = 'CYCLES_GET_SUCCESS';
export const CYCLES_GET_FAILURE = 'CYCLES_GET_FAILURE';

export const CYCLE_GET_REQUEST = 'CYCLE_GET_REQUEST';
export const CYCLE_GET_SUCCESS = 'CYCLE_GET_SUCCESS';
export const CYCLE_GET_FAILURE = 'CYCLE_GET_FAILURE';

export const CYCLES_BY_TEAM_REQUEST = 'CYCLES_BY_TEAM_REQUEST';
export const CYCLES_BY_TEAM_SUCCESS = 'CYCLES_BY_TEAM_SUCCESS';
export const CYCLES_BY_TEAM_FAILURE = 'CYCLES_BY_TEAM_FAILURE';

export const CYCLES_QUERY_CURRENT_BY_TEAM_REQUEST =
  'CYCLES_QUERY_CURRENT_BY_TEAM_REQUEST';
export const CYCLES_QUERY_CURRENT_BY_TEAM_SUCCESS =
  'CYCLES_QUERY_CURRENT_BY_TEAM_SUCCESS';
export const CYCLES_QUERY_CURRENT_BY_TEAM_FAILURE =
  'CYCLES_QUERY_CURRENT_BY_TEAM_FAILURE';

export const CYCLE_LOADING_REQUEST_ACTIONS = /^CYCLES?_(GET|BY_TEAM)_REQUEST$/;
export const CYCLE_LOADING_SUCCESS_ACTIONS = /^CYCLES?_(GET|BY_TEAM)_SUCCESS$/;
export const CYCLE_LOADING_FAILURE_ACTIONS = /^CYCLES?_(GET|BY_TEAM)_FAILURE$/;

export const CYCLE_ADD_REQUEST = 'CYCLE_ADD_REQUEST';
export const CYCLE_ADD_SUCCESS = 'CYCLE_ADD_SUCCESS';
export const CYCLE_ADD_FAILURE = 'CYCLE_ADD_FAILURE';

export const CYCLE_UPDATE_REQUEST = 'CYCLE_UPDATE_REQUEST';
export const CYCLE_UPDATE_SUCCESS = 'CYCLE_UPDATE_SUCCESS';
export const CYCLE_UPDATE_FAILURE = 'CYCLE_UPDATE_FAILURE';

export const CYCLE_REMOVE_REQUEST = 'CYCLE_REMOVE_REQUEST';
export const CYCLE_REMOVE_SUCCESS = 'CYCLE_REMOVE_SUCCESS';
export const CYCLE_REMOVE_FAILURE = 'CYCLE_REMOVE_FAILURE';

export const CYCLE_AU_REQUEST_ACTIONS = /^CYCLE_(ADD|UPDATE)_REQUEST$/;
export const CYCLE_AU_SUCCESS_ACTIONS = /^CYCLE_(ADD|UPDATE)_SUCCESS$/;
export const CYCLE_AU_FAILURE_ACTIONS = /^CYCLE_(ADD|UPDATE)_FAILURE$/;

export const CYCLE_QUERY_PARTICIPATION_BY_TEAM_REQUEST =
  'CYCLE_QUERY_PARTICIPATION_BY_TEAM_REQUEST';
export const CYCLE_QUERY_PARTICIPATION_BY_TEAM_SUCCESS =
  'CYCLE_QUERY_PARTICIPATION_BY_TEAM_SUCCESS';
export const CYCLE_QUERY_PARTICIPATION_BY_TEAM_FAILURE =
  'CYCLE_QUERY_PARTICIPATION_BY_TEAM_FAILURE';

export const CYCLES_PARTICIPATION_BY_USER_REQUEST =
  'CYCLES_PARTICIPATION_BY_USER_REQUEST';
export const CYCLES_PARTICIPATION_BY_USER_SUCCESS =
  'CYCLES_PARTICIPATION_BY_USER_SUCCESS';
export const CYCLES_PARTICIPATION_BY_USER_FAILURE =
  'CYCLES_PARTICIPATION_BY_USER_FAILURE';

export const CYCLE_QUERY_COMPLETION_BY_CLASSROOM_REQUEST =
  'CYCLE_QUERY_COMPLETION_BY_CLASSROOM_REQUEST';
export const CYCLE_QUERY_COMPLETION_BY_CLASSROOM_SUCCESS =
  'CYCLE_QUERY_COMPLETION_BY_CLASSROOM_SUCCESS';
export const CYCLE_QUERY_COMPLETION_BY_CLASSROOM_FAILURE =
  'CYCLE_QUERY_COMPLETION_BY_CLASSROOM_FAILURE';
