export const RESPONSES_GET_REQUEST = 'RESPONSES_GET_REQUEST';
export const RESPONSES_GET_SUCCESS = 'RESPONSES_GET_SUCCESS';
export const RESPONSES_GET_FAILURE = 'RESPONSES_GET_FAILURE';

export const RESPONSES_BY_TEAM_REQUEST = 'RESPONSES_BY_TEAM_REQUEST';
export const RESPONSES_BY_TEAM_SUCCESS = 'RESPONSES_BY_TEAM_SUCCESS';
export const RESPONSES_BY_TEAM_FAILURE = 'RESPONSES_BY_TEAM_FAILURE';

export const RESPONSES_ADD_REQUEST = 'RESPONSES_ADD_REQUEST';
export const RESPONSES_ADD_SUCCESS = 'RESPONSES_ADD_SUCCESS';
export const RESPONSES_ADD_FAILURE = 'RESPONSES_ADD_FAILURE';

export const RESPONSES_UPDATE_REQUEST = 'RESPONSES_UPDATE_REQUEST';
export const RESPONSES_UPDATE_SUCCESS = 'RESPONSES_UPDATE_SUCCESS';
export const RESPONSES_UPDATE_FAILURE = 'RESPONSES_UPDATE_FAILURE';

export const RESPONSES_REQUEST_ACTIONS = /^RESPONSES_\w+_REQUEST$/;
export const RESPONSES_SUCCESS_ACTIONS = /^RESPONSES_\w+_SUCCESS$/;
export const RESPONSES_FAILURE_ACTIONS = /^RESPONSES_\w+_FAILURE$/;

export const RESPONSES_AU_REQUEST_ACTIONS = /^RESPONSES_(ADD|UPDATE)_REQUEST$/;
export const RESPONSES_AU_SUCCESS_ACTIONS = /^RESPONSES_(ADD|UPDATE)_SUCCESS$/;
export const RESPONSES_AU_FAILURE_ACTIONS = /^RESPONSES_(ADD|UPDATE)_FAILURE$/;
