export const SURVEY_BY_TEAM_REQUEST = 'SURVEY_BY_TEAM_REQUEST';
export const SURVEY_BY_TEAM_SUCCESS = 'SURVEY_BY_TEAM_SUCCESS';
export const SURVEY_BY_TEAM_FAILURE = 'SURVEY_BY_TEAM_FAILURE';

export const SURVEY_GET_REQUEST = 'SURVEY_GET_REQUEST';
export const SURVEY_GET_SUCCESS = 'SURVEY_GET_SUCCESS';
export const SURVEY_GET_FAILURE = 'SURVEY_GET_FAILURE';

export const SURVEY_UPDATE_REQUEST = 'SURVEY_UPDATE_REQUEST';
export const SURVEY_UPDATE_SUCCESS = 'SURVEY_UPDATE_SUCCESS';
export const SURVEY_UPDATE_FAILURE = 'SURVEY_UPDATE_FAILURE';

export const SURVEY_REQUEST_ACTIONS = /^SURVEY_\w+_REQUEST$/;
export const SURVEY_SUCCESS_ACTIONS = /^SURVEY_\w+_SUCCESS$/;
export const SURVEY_FAILURE_ACTIONS = /^SURVEY_\w+_FAILURE$/;
