export const ALL_USER_DIGESTS_REQUEST = 'ALL_USER_DIGESTS_FAILURE';
export const UNREAD_USER_DIGESTS_REQUEST = 'UNREAD_USER_DIGESTS_REQUEST';
export const USER_DIGESTS_SUCCESS = 'USER_DIGESTS_SUCCESS';
export const USER_DIGESTS_FAILURE = 'USER_DIGESTS_FAILURE';

export const UPDATE_DIGEST_REQUEST = 'UPDATE_DIGEST_REQUEST';
export const UPDATE_DIGEST_SUCCESS = 'UPDATE_DIGEST_SUCCESS';
export const UPDATE_DIGEST_FAILURE = 'UPDATE_DIGEST_FAILURE';
