export const REMOVE_TEAM_USER_REQUEST = 'REMOVE_TEAM_USER_REQUEST';
export const REMOVE_TEAM_USER_SUCCESS = 'REMOVE_TEAM_USER_SUCCESS';
export const REMOVE_TEAM_USER_FAILURE = 'REMOVE_TEAM_USER_FAILURE';

export const REMOVE_ORGANIZATION_USER_REQUEST =
  'REMOVE_ORGANIZATION_USER_REQUEST';
export const REMOVE_ORGANIZATION_USER_SUCCESS =
  'REMOVE_ORGANIZATION_USER_SUCCESS';
export const REMOVE_ORGANIZATION_USER_FAILURE =
  'REMOVE_ORGANIZATION_USER_FAILURE';

export const LEAVE_TEAM_REQUEST = 'LEAVE_TEAM_REQUEST';
export const LEAVE_TEAM_SUCCESS = 'LEAVE_TEAM_SUCCESS';
export const LEAVE_TEAM_FAILURE = 'LEAVE_TEAM_FAILURE';

export const LEAVE_ORGANIZATION_REQUEST = 'LEAVE_ORGANIZATION_REQUEST';
export const LEAVE_ORGANIZATION_SUCCESS = 'LEAVE_ORGANIZATION_SUCCESS';
export const LEAVE_ORGANIZATION_FAILURE = 'LEAVE_ORGANIZATION_FAILURE';

export const TEAM_ATTACH_ORGANIZATION_REQUEST =
  'TEAM_ATTACH_ORGANIZATION_REQUEST';
export const TEAM_ATTACH_ORGANIZATION_SUCCESS =
  'TEAM_ATTACH_ORGANIZATION_SUCCESS';
export const TEAM_ATTACH_ORGANIZATION_FAILURE =
  'TEAM_ATTACH_ORGANIZATION_FAILURE';
