export const USERS_BY_TEAM_REQUEST = 'USERS_BY_TEAM_REQUEST';
export const USERS_BY_TEAM_SUCCESS = 'USERS_BY_TEAM_SUCCESS';
export const USERS_BY_TEAM_FAILURE = 'USERS_BY_TEAM_FAILURE';
export const usersByTeamResult = [USERS_BY_TEAM_SUCCESS, USERS_BY_TEAM_FAILURE];

export const USERS_BY_ORGANIZATION_REQUEST = 'USERS_BY_ORGANIZATION_REQUEST';
export const USERS_BY_ORGANIZATION_SUCCESS = 'USERS_BY_ORGANIZATION_SUCCESS';
export const USERS_BY_ORGANIZATION_FAILURE = 'USERS_BY_ORGANIZATION_FAILURE';

export const USER_REQUEST = 'USER_REQUEST';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_FAILURE = 'USER_FAILURE';

export const INVITE_USERS_REQUEST = 'INVITE_USERS_REQUEST';
export const INVITE_USERS_SUCCESS = 'INVITE_USERS_SUCCESS';
export const INVITE_USERS_FAILURE = 'INVITE_USERS_FAILURE';

export const INVITE_ORGANIZATION_USER_REQUEST =
  'INVITE_ORGANIZATION_USER_REQUEST';
export const INVITE_ORGANIZATION_USER_SUCCESS =
  'INVITE_ORGANIZATION_USER_SUCCESS';
export const INVITE_ORGANIZATION_USER_FAILURE =
  'INVITE_ORGANIZATION_USER_FAILURE';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const UPDATE_USERS_REQUEST = 'UPDATE_USERS_REQUEST';
export const UPDATE_USERS_SUCCESS = 'UPDATE_USERS_SUCCESS';
export const UPDATE_USERS_FAILURE = 'UPDATE_USERS_FAILURE';

export const USER_MODE_SET = 'USER_MODE_SET';
export const USER_MODE_RESET = 'USER_MODE_RESET';

export const STAGE_INVITEE = 'STAGE_INVITEE';
export const UNSTAGE_INVITEE = 'UNSTAGE_INVITEE';
export const UNSTAGE_INVITEES = 'UNSTAGE_INVITEES';

export const CHECK_USER_EXISTS_REQUEST = 'CHECK_USER_EXISTS_REQUEST';
export const CHECK_USER_EXISTS_SUCCESS = 'CHECK_USER_EXISTS_SUCCESS';
export const CHECK_USER_EXISTS_FAILURE = 'CHECK_USER_EXISTS_FAILURE';

export const VERIFY_USERS_REQUEST = 'VERIFY_USERS_REQUEST';
export const VERIFY_USERS_SUCCESS = 'VERIFY_USERS_SUCCESS';
export const VERIFY_USERS_FAILURE = 'VERIFY_USERS_FAILURE';
